# Generated by Django 5.2.6 on 2025-09-22 18:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_sistema_tecnico_cliente_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('CONTRATO', 'Contrato'), ('VITALICIO', 'Vitalício'), ('CONTRATO_WEB', 'Contrato Web'), ('OUTRO', 'Outro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_associados', to='inventario.tecnico'),
        ),
        migrations.CreateModel(
            name='ServicoRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_servico', models.DateField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('finalizado', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.cliente')),
                ('verificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.tecnico')),
            ],
            options={
                'ordering': ['-data_servico'],
            },
        ),
    ]
